---

- name: "KeepAliveD.Check - Create Vault Check Script directory"
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - keepalived_checkscript_scripts | selectattr('command', 'undefined') | list | length > 0
  ansible.builtin.file:
    path: "{{ keepalived_checkscript_path }}"
    state: directory
    owner: "{{ keepalived_checkscript_user }}"
    group: "{{ keepalived_checkscript_group }}"
    mode: '0700'

- name: "KeepAliveD.Check - Create Vault Check Scripts"
  become: true
  notify:
    - "KeepAliveD Restart"
  loop: "{{ keepalived_checkscript_scripts }}"
  loop_control:
    label: "{{ item.command | default(item.filename) }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - item.command is not defined
    - item.content is defined and item.content | length > 1
  ansible.builtin.copy:
    dest: "{{ keepalived_checkscript_path }}/{{ item.filename }}"
    content: "{{ item.content }}"
    owner: "{{ keepalived_checkscript_user }}"
    group: "{{ keepalived_checkscript_group }}"
    mode: "{{ item.mode | string | default('0700') }}"
