---

# - name: "KeepAliveD.UFW - Configure the kernel to keep connections alive on UFW changes"
#   become: true
#   ansible.posix.sysctl:
#     name: net.netfilter.nf_conntrack_tcp_be_liberal
#     value: 1
#     state: present
#     sysctl_set: true
#     reload: true

- name: "KeepAliveD.UFW - Edit UFW before.rules to allow Ah and vrrp"
  become: true
  ansible.builtin.blockinfile:
    path: '/etc/ufw/before.rules'
    insertbefore: "# don't delete the 'COMMIT' line or these rules won't be processed"
    block: |
      # Required rules for KeepAliveD
      {% for vrrp_inst in keepalived_vrrp %}
      {% for vip in vrrp_inst.vip %}
      -A ufw-before-output -p Ah -d {{ vip | ansible.utils.ipaddr }} -j ACCEPT
      -A ufw-before-output -p vrrp -d {{ vip | ansible.utils.ipaddr }} -j ACCEPT
      {% endfor %}
      {% if keepalived_unicast_mode | bool and vrrp_inst.unicast_peer is defined and vrrp_inst.unicast_peer | length > 0 %}
      {% for peer in vrrp_inst.unicast_peer %}
      -A ufw-before-output -p Ah -d {{ peer | ansible.utils.ipaddr }} -j ACCEPT
      -A ufw-before-output -p vrrp -d {{ peer | ansible.utils.ipaddr }} -j ACCEPT
      {% endfor %}
      {% endif %}
      {% endfor %}
  notify: "UFW Reload"
